[package]
name = 'calculator'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0xcfde0a21a29fe95a27c91f2729f7a591e79aea65be8c97bd35ad484e40b769c5"
std = "0x1"